<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0-desktop;net10.0-desktop</TargetFrameworks>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>

        <!-- Display name -->
        <ApplicationTitle>MiniBanque.Client</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>be.hel-is3.minibanque-client</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>MiniBanque.Client</ApplicationPublisher>
        <!-- Package Description -->
        <Description>MiniBanque.Client powered by Uno Platform.</Description>

        <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
        <UnoFeatures>
            Lottie;
            Toolkit;
            Mvvm;
            ThemeService;
            SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>
    <ItemGroup>
        <Folder Include="ViewModels\" />
    </ItemGroup>
    <ItemGroup>
        <Page Update="View\LoginPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="View\DashboardPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="View\RegisterPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="View\TransferPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="View\HistoryPage.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>

</Project>
